Abyssalcraft.ws
ActuallyAdditions.ws
AppliedEnergistics.ws
AstralSorcery.ws
Avaritia.ws
BetterWithMods.ws
BloodMagic.ws
Botania.ws
CharcoalPit.ws
DraconicEvolution.ws
EnviormentalTech.ws
ExtraUtils2.ws
GalacticCraft.ws
ImmersiveEngineering.ws
IndustrialForegoing.ws
Mekanism.ws
Minecraft.ws
NuclearCraft.ws
OreStages.ws
PneumaticCraft.ws
TConstruct.ws
TechReborn.ws
ThermalExpansion.ws